name: stac-access
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- python=3.10.10
- pip
- jupyterlab=3.6.*
- dask=2023.4.*
- distributed=2023.4.*
- datacube=1.8.12
- stackstac=0.4.3
- odc-stac=0.3.5
- odc-geo=0.3.3
- pystac=1.7.*
- pystac-client=0.6.*
- rioxarray=0.14.*
- rasterio=1.3.6
- numpy=1.23.*
- numba=0.56.*
- dask-jobqueue
- fiona
- matplotlib

