name: stac-access
channels:
- conda-forge
dependencies:
- python=3.10.*
- pip
- jupyterlab=3.6.*
- dask=2023.5.*
- distributed=2023.5.*
- datacube=1.8.*
- stackstac=0.4.*
- odc-stac=0.3.*
- odc-geo=0.3.*
- pystac=1.7.*
- pystac-client=0.6.*
- rioxarray=0.14.*
- rasterio=1.3.*
- numpy=1.24.*
- numba=0.57.*
- dask-jobqueue
- fiona
- matplotlib
